### PR TITLE
Update get_cache import to work with Django1.9

### PR DESCRIPTION
**Pull request by DylanYoung**
Address Issue: GH-1

### CODE REVIEW

**Comment by DylanYoung** [comment]
We could also check the Django version to determine the appropriate import statement, but this seemed more pythonic.

**Comment by wolfe** [comment]
P.S.  Maybe proofread the README if you have a chance?

**Comment by wolfe** [comment]
P.S. Maybe proofread the README if you have a chance?

**Comment by wolfe** [comment]
Closing as no longer valid.  Sorry I didn't take care of it.

**Pull request closed without merging**
